### PR TITLE
Added Dropdowns and Div2

### PR DESCRIPTION
**Pull request by sparshsharma2510**
I have added Dropdowns and the second div on our create page. But I've noticed that the area to type in the lyrics and the song background is not wide enough for the user to comfortably type.

Preview:
image

 Let me know what you think about it.

### CODE REVIEW

**Comment by Pushpit07** [comment]
This is fine

**Comment by Pushpit07** [comment]
What we can do is display modals on clicking these boxes

**Comment by Pushpit07** [comment]
And manage the content of the textarea and modal by using a single React state. What say?

**Comment by sparshsharma2510** [comment]
Works for me!

**Pull request merged**
