### PR TITLE
Added upload cover image div

### PR DESCRIPTION
**Pull request by sparshsharma2510**
I have created a separate route for the create page and have added the upload image div component to it. Kindly check and merge if it seems fine and let me know if we want to change anything.

### CODE REVIEW

**Comment by Pushpit07** [comment]
How can the user know that the image is uploaded? Can we get a preview of the uploaded image on the web?

**Comment by sparshsharma2510** [comment]
I'll try to do something about this.

**Comment by sparshsharma2510** [comment]
@Pushpit07 I tried many different ways to implement the preview feature and fortunately, one of them worked. 
I was also working on the upload song div so, I thought of adding a kind of the same functionality on the upload song label also.
Here's the current preview of the upload labels. 

image

**Comment by Yuvrajchandra** [comment]
This looks good @sparshsharma2510 
We can proceed with it!

**Review by Pushpit07 — APPROVED** [review]

**Comment by Pushpit07** [comment]
Are you working on the responsiveness too?

**Comment by sparshsharma2510** [comment]
@Pushpit07 not yet. Once we have all the components of the create page in place, then I'll start my work with responsiveness.

**Pull request merged**
